CREATE TABLE USERINFO(
ID INT PRIMARY KEY,
USERNAME INT,
PASSWORD VARCHAR(100),
EMAIL VARCHAR(100),
PROFILE INT
);

CREATE TABLE EMPPROFILE(
ID INT PRIMARY KEY,
NAME VARCHAR(100),
DESIG VARCHAR(100),
SL VARCHAR(100),
ROLE VARCHAR(100)
);

ALTER TABLE USERINFO ADD
FOREIGN KEY(PROFILE) REFERENCES EMPPROFILE(ID)